### ISSUE TITLE
license

### ISSUE THREAD

**Issue by jellelicht** [ito-org/react-native-ito-bluetooth#7]
It is unclear under which license this code is distributed

**Comment by jellelicht** [comment]
(A random string in a build file saying "MIT" is not enough)

**Comment by nicorikken** [comment]
Jup, better than nothing at least. I would recommend a check using the [REUSE license tool](https://reuse.software/ ) which can also earn you a GitHub badge. But providing the source code under any free software license is more important at this time than doing it according to best-practices.

I already see an effort ongoing in https://github.com/ito-org/react-native-ito-bluetooth/pull/8
